### ISSUE TITLE
Support for 13.0.3

### ISSUE THREAD

**Issue by userbouy** [ThatNintendoNerd/stage_config#3]
Nintendo once again updated smash ultimate 13.0.3. While most essential plugins have been updated as well, stage alts haven't (of which this plugin is part of). So, could you please update it?

**Comment by ThatNintendoNerd** [comment]
This plugin does not need to be updated for Ver. 13.0.3 due to its reliable offset searching. The `discard_stage_code` feature would have broken like it did when Ver. 13.0.2 released, but thankfully the read-only data segment within the game's main executable did not get shifted this time around. Consequently, the relevant fallback offset still holds up when searching for offsets with the provided bytecode. I plan to update the fallback offsets and bytecode in a future commit purely for maintenance.

I'm not sure what you mean by this plugin being part of the Stage Alts project, as the two are independent of each other.
